/**
 * Utility to convert emoji to OpenMoji SVG URL
 * OpenMoji uses lowercase hex codepoints in filenames
 * CDN: https://cdn.jsdelivr.net/npm/openmoji@latest/color/svg/
 * 
 * @param emoji - The emoji string (e.g., '🏠')
 * @returns The OpenMoji SVG URL
 */
export function getOpenMojiUrl(emoji: string): string {
  // Use Array.from to handle surrogate pairs correctly
  const codePoints: number[] = [];
  for (const char of emoji) {
    const codePoint = char.codePointAt(0);
    if (codePoint !== undefined) {
      codePoints.push(codePoint);
    }
  }
  
  // Convert to lowercase hex with proper padding
  // OpenMoji files use lowercase hex separated by '-' for sequences
  const codepoint = codePoints
    .map(cp => cp.toString(16).toLowerCase().padStart(4, '0'))
    .join('-');
  
  // Return OpenMoji CDN URL
  return `https://cdn.jsdelivr.net/npm/openmoji@latest/color/svg/${codepoint}.svg`;
}

/**
 * Comprehensive emoji data with searchable names/keywords
 */
export interface EmojiData {
  emoji: string;
  name: string;
  keywords: string[];
  category?: string;
}

/**
 * Expanded emoji options with searchable metadata
 * Duplicates are filtered out - only the first occurrence of each emoji is kept
 */
const EMOJI_DATA_RAW: EmojiData[] = [
  // Smileys & Emotion
  { emoji: '😀', name: 'Grinning Face', keywords: ['smile', 'happy', 'joy', 'laugh'] },
  { emoji: '😊', name: 'Smiling Face with Smiling Eyes', keywords: ['smile', 'happy', 'cute'] },
  { emoji: '😍', name: 'Heart Eyes', keywords: ['love', 'heart', 'infatuated'] },
  { emoji: '🤔', name: 'Thinking Face', keywords: ['think', 'question', 'ponder'] },
  { emoji: '😎', name: 'Smiling Face with Sunglasses', keywords: ['cool', 'shades', 'awesome'] },
  { emoji: '🥳', name: 'Partying Face', keywords: ['party', 'celebration', 'birthday'] },
  { emoji: '😴', name: 'Sleeping Face', keywords: ['sleep', 'tired', 'rest'] },
  { emoji: '😢', name: 'Crying Face', keywords: ['sad', 'tears', 'cry'] },
  
  // Objects & Symbols
  { emoji: '📝', name: 'Memo', keywords: ['note', 'write', 'document', 'text'] },
  { emoji: '📋', name: 'Clipboard', keywords: ['clipboard', 'list', 'checklist'] },
  { emoji: '📅', name: 'Calendar', keywords: ['calendar', 'date', 'schedule', 'event'] },
  { emoji: '📊', name: 'Bar Chart', keywords: ['chart', 'graph', 'data', 'analytics'] },
  { emoji: '📌', name: 'Pushpin', keywords: ['pin', 'mark', 'location'] },
  { emoji: '📎', name: 'Paperclip', keywords: ['attachment', 'clip', 'file'] },
  { emoji: '🔖', name: 'Bookmark', keywords: ['bookmark', 'save', 'mark'] },
  { emoji: '📖', name: 'Open Book', keywords: ['book', 'read', 'study'] },
  { emoji: '📚', name: 'Books', keywords: ['books', 'library', 'study', 'education'] },
  { emoji: '📄', name: 'Page Facing Up', keywords: ['document', 'page', 'file'] },
  { emoji: '📁', name: 'File Folder', keywords: ['folder', 'directory', 'files'] },
  { emoji: '💾', name: 'Floppy Disk', keywords: ['save', 'disk', 'storage'] },
  { emoji: '🔍', name: 'Magnifying Glass', keywords: ['search', 'find', 'look'] },
  { emoji: '✏️', name: 'Pencil', keywords: ['write', 'edit', 'pencil'] },
  { emoji: '✒️', name: 'Black Nib', keywords: ['pen', 'write', 'ink'] },
  { emoji: '🖊️', name: 'Pen', keywords: ['pen', 'write'] },
  { emoji: '🖍️', name: 'Crayon', keywords: ['crayon', 'color', 'draw'] },
  { emoji: '📝', name: 'Memo', keywords: ['memo', 'note', 'write'] },
  
  // Activities
  { emoji: '🎯', name: 'Direct Hit', keywords: ['target', 'goal', 'aim', 'focus'] },
  { emoji: '🎨', name: 'Artist Palette', keywords: ['art', 'paint', 'creative', 'design'] },
  { emoji: '🎬', name: 'Movie Camera', keywords: ['movie', 'film', 'video'] },
  { emoji: '🎮', name: 'Video Game', keywords: ['game', 'play', 'gaming'] },
  { emoji: '🎲', name: 'Game Die', keywords: ['dice', 'game', 'random'] },
  { emoji: '🎪', name: 'Circus Tent', keywords: ['circus', 'entertainment'] },
  { emoji: '🎭', name: 'Performing Arts', keywords: ['theater', 'drama', 'performance'] },
  { emoji: '🎨', name: 'Artist Palette', keywords: ['art', 'creative'] },
  
  // Travel & Places
  { emoji: '🏠', name: 'House', keywords: ['home', 'house', 'residence'] },
  { emoji: '🏢', name: 'Office Building', keywords: ['office', 'work', 'business'] },
  { emoji: '🏫', name: 'School', keywords: ['school', 'education', 'learning'] },
  { emoji: '🏥', name: 'Hospital', keywords: ['hospital', 'health', 'medical'] },
  { emoji: '🏪', name: 'Convenience Store', keywords: ['store', 'shop'] },
  { emoji: '🏬', name: 'Department Store', keywords: ['store', 'shop', 'mall'] },
  { emoji: '🚀', name: 'Rocket', keywords: ['rocket', 'launch', 'space', 'fast', 'speed'] },
  { emoji: '✈️', name: 'Airplane', keywords: ['plane', 'travel', 'flight'] },
  { emoji: '🚗', name: 'Car', keywords: ['car', 'vehicle', 'drive'] },
  { emoji: '🚕', name: 'Taxi', keywords: ['taxi', 'cab', 'transport'] },
  { emoji: '🚌', name: 'Bus', keywords: ['bus', 'transport'] },
  { emoji: '🚲', name: 'Bicycle', keywords: ['bike', 'cycling'] },
  { emoji: '🏍️', name: 'Motorcycle', keywords: ['motorcycle', 'bike'] },
  { emoji: '🛴', name: 'Kick Scooter', keywords: ['scooter'] },
  
  // Food & Drink
  { emoji: '☕', name: 'Hot Beverage', keywords: ['coffee', 'tea', 'drink'] },
  { emoji: '🍕', name: 'Pizza', keywords: ['pizza', 'food'] },
  { emoji: '🍔', name: 'Hamburger', keywords: ['burger', 'food'] },
  { emoji: '🍟', name: 'French Fries', keywords: ['fries', 'food'] },
  { emoji: '🍰', name: 'Shortcake', keywords: ['cake', 'dessert', 'sweet'] },
  { emoji: '🎂', name: 'Birthday Cake', keywords: ['birthday', 'cake', 'celebration'] },
  { emoji: '🍎', name: 'Red Apple', keywords: ['apple', 'fruit'] },
  { emoji: '🍊', name: 'Tangerine', keywords: ['orange', 'fruit'] },
  { emoji: '🍋', name: 'Lemon', keywords: ['lemon', 'fruit'] },
  { emoji: '🍌', name: 'Banana', keywords: ['banana', 'fruit'] },
  { emoji: '🍉', name: 'Watermelon', keywords: ['watermelon', 'fruit'] },
  
  // Nature
  { emoji: '🌱', name: 'Seedling', keywords: ['plant', 'growth', 'new'] },
  { emoji: '🌲', name: 'Evergreen Tree', keywords: ['tree', 'nature'] },
  { emoji: '🌳', name: 'Deciduous Tree', keywords: ['tree', 'nature'] },
  { emoji: '🌴', name: 'Palm Tree', keywords: ['palm', 'tropical', 'beach'] },
  { emoji: '🌵', name: 'Cactus', keywords: ['cactus', 'desert'] },
  { emoji: '🌷', name: 'Tulip', keywords: ['flower', 'tulip'] },
  { emoji: '🌹', name: 'Rose', keywords: ['rose', 'flower', 'love'] },
  { emoji: '🌺', name: 'Hibiscus', keywords: ['flower', 'hibiscus'] },
  { emoji: '🌸', name: 'Cherry Blossom', keywords: ['flower', 'cherry', 'spring'] },
  { emoji: '🌻', name: 'Sunflower', keywords: ['sunflower', 'flower'] },
  { emoji: '🌼', name: 'Daisy', keywords: ['daisy', 'flower'] },
  { emoji: '⚡', name: 'High Voltage', keywords: ['lightning', 'electric', 'energy', 'power', 'bolt'] },
  { emoji: '🔥', name: 'Fire', keywords: ['fire', 'hot', 'burn', 'flame', 'energy'] },
  { emoji: '💧', name: 'Droplet', keywords: ['water', 'drop', 'liquid'] },
  { emoji: '☀️', name: 'Sun', keywords: ['sun', 'sunny', 'weather'] },
  { emoji: '⭐', name: 'Star', keywords: ['star', 'favorite', 'rating'] },
  { emoji: '🌟', name: 'Glowing Star', keywords: ['star', 'shining', 'bright', 'special'] },
  { emoji: '✨', name: 'Sparkles', keywords: ['sparkle', 'magic', 'shiny', 'glitter'] },
  { emoji: '🌙', name: 'Crescent Moon', keywords: ['moon', 'night'] },
  { emoji: '🌈', name: 'Rainbow', keywords: ['rainbow', 'colorful', 'pride'] },
  
  // Objects
  { emoji: '💡', name: 'Light Bulb', keywords: ['idea', 'light', 'inspiration', 'creative'] },
  { emoji: '💻', name: 'Laptop', keywords: ['laptop', 'computer', 'tech', 'coding'] },
  { emoji: '🖥️', name: 'Desktop Computer', keywords: ['computer', 'desktop', 'pc'] },
  { emoji: '⌨️', name: 'Keyboard', keywords: ['keyboard', 'type', 'input'] },
  { emoji: '🖱️', name: 'Computer Mouse', keywords: ['mouse', 'computer'] },
  { emoji: '📱', name: 'Mobile Phone', keywords: ['phone', 'mobile', 'cell'] },
  { emoji: '📞', name: 'Telephone', keywords: ['phone', 'call', 'telephone'] },
  { emoji: '📠', name: 'Fax Machine', keywords: ['fax', 'machine'] },
  { emoji: '📺', name: 'Television', keywords: ['tv', 'television'] },
  { emoji: '📻', name: 'Radio', keywords: ['radio', 'music'] },
  { emoji: '🎧', name: 'Headphone', keywords: ['headphone', 'music', 'audio'] },
  { emoji: '🔊', name: 'Speaker High Volume', keywords: ['speaker', 'sound', 'volume'] },
  { emoji: '🔔', name: 'Bell', keywords: ['bell', 'notification', 'alert'] },
  { emoji: '⏰', name: 'Alarm Clock', keywords: ['alarm', 'time', 'wake'] },
  { emoji: '🕐', name: 'One O\'Clock', keywords: ['clock', 'time'] },
  { emoji: '⏱️', name: 'Stopwatch', keywords: ['stopwatch', 'timer', 'time'] },
  { emoji: '⏲️', name: 'Timer Clock', keywords: ['timer', 'clock'] },
  { emoji: '📷', name: 'Camera', keywords: ['camera', 'photo', 'picture'] },
  { emoji: '📹', name: 'Video Camera', keywords: ['video', 'camera', 'recording'] },
  { emoji: '🔦', name: 'Flashlight', keywords: ['flashlight', 'torch', 'light'] },
  { emoji: '🕯️', name: 'Candle', keywords: ['candle', 'light'] },
  { emoji: '🔋', name: 'Battery', keywords: ['battery', 'power', 'energy'] },
  { emoji: '🔌', name: 'Electric Plug', keywords: ['plug', 'electric', 'power'] },
  { emoji: '💿', name: 'Optical Disk', keywords: ['cd', 'disk', 'music'] },
  { emoji: '💾', name: 'Floppy Disk', keywords: ['floppy', 'disk', 'save'] },
  { emoji: '💿', name: 'Optical Disk', keywords: ['dvd', 'disk'] },
  
  // Symbols
  { emoji: '❤️', name: 'Red Heart', keywords: ['heart', 'love', 'red'] },
  { emoji: '🧡', name: 'Orange Heart', keywords: ['heart', 'orange'] },
  { emoji: '💛', name: 'Yellow Heart', keywords: ['heart', 'yellow'] },
  { emoji: '💚', name: 'Green Heart', keywords: ['heart', 'green'] },
  { emoji: '💙', name: 'Blue Heart', keywords: ['heart', 'blue'] },
  { emoji: '💜', name: 'Purple Heart', keywords: ['heart', 'purple'] },
  { emoji: '🖤', name: 'Black Heart', keywords: ['heart', 'black'] },
  { emoji: '🤍', name: 'White Heart', keywords: ['heart', 'white'] },
  { emoji: '💔', name: 'Broken Heart', keywords: ['broken', 'heart', 'sad'] },
  { emoji: '💯', name: 'Hundred Points', keywords: ['100', 'perfect', 'score'] },
  { emoji: '✅', name: 'Check Mark Button', keywords: ['check', 'mark', 'correct', 'done'] },
  { emoji: '✔️', name: 'Check Mark', keywords: ['check', 'mark'] },
  { emoji: '❌', name: 'Cross Mark', keywords: ['cross', 'wrong', 'no'] },
  { emoji: '❓', name: 'Question Mark', keywords: ['question', 'help'] },
  { emoji: '❗', name: 'Exclamation Mark', keywords: ['exclamation', 'warning'] },
  { emoji: '‼️', name: 'Double Exclamation Mark', keywords: ['exclamation', 'urgent'] },
  { emoji: '➕', name: 'Plus', keywords: ['plus', 'add', 'more'] },
  { emoji: '➖', name: 'Minus', keywords: ['minus', 'subtract', 'less'] },
  { emoji: '✖️', name: 'Multiply', keywords: ['multiply', 'times'] },
  { emoji: '➗', name: 'Divide', keywords: ['divide', 'split'] },
  { emoji: '💯', name: 'Hundred Points', keywords: ['100', 'perfect'] },
  
  // Flags
  { emoji: '🎌', name: 'Crossed Flags', keywords: ['flags', 'japan'] },
  { emoji: '🏳️', name: 'White Flag', keywords: ['flag', 'white', 'surrender'] },
  { emoji: '🏴', name: 'Black Flag', keywords: ['flag', 'black'] },
  { emoji: '🏁', name: 'Chequered Flag', keywords: ['flag', 'race', 'finish'] },
  { emoji: '🚩', name: 'Triangular Flag', keywords: ['flag', 'red'] },
  
  // Activities & Events
  { emoji: '🎉', name: 'Party Popper', keywords: ['party', 'celebration', 'congratulations', 'yay'] },
  { emoji: '🎊', name: 'Confetti Ball', keywords: ['confetti', 'celebration', 'party'] },
  { emoji: '🎈', name: 'Balloon', keywords: ['balloon', 'party', 'celebration'] },
  { emoji: '🎁', name: 'Wrapped Gift', keywords: ['gift', 'present', 'birthday'] },
  { emoji: '🎀', name: 'Ribbon', keywords: ['ribbon', 'bow'] },
  { emoji: '🎗️', name: 'Reminder Ribbon', keywords: ['ribbon', 'reminder'] },
  { emoji: '🏆', name: 'Trophy', keywords: ['trophy', 'win', 'award', 'champion'] },
  { emoji: '🥇', name: '1st Place Medal', keywords: ['gold', 'medal', 'first', 'win'] },
  { emoji: '🥈', name: '2nd Place Medal', keywords: ['silver', 'medal', 'second'] },
  { emoji: '🥉', name: '3rd Place Medal', keywords: ['bronze', 'medal', 'third'] },
  { emoji: '⚽', name: 'Soccer Ball', keywords: ['soccer', 'football', 'sport'] },
  { emoji: '🏀', name: 'Basketball', keywords: ['basketball', 'sport'] },
  { emoji: '🏈', name: 'American Football', keywords: ['football', 'american', 'sport'] },
  { emoji: '⚾', name: 'Baseball', keywords: ['baseball', 'sport'] },
  { emoji: '🎾', name: 'Tennis', keywords: ['tennis', 'sport'] },
  { emoji: '🏐', name: 'Volleyball', keywords: ['volleyball', 'sport'] },
  { emoji: '🏓', name: 'Ping Pong', keywords: ['ping', 'pong', 'table', 'tennis'] },
  { emoji: '🏸', name: 'Badminton', keywords: ['badminton', 'sport'] },
  { emoji: '🥊', name: 'Boxing Glove', keywords: ['boxing', 'sport'] },
  { emoji: '🥋', name: 'Martial Arts Uniform', keywords: ['martial', 'arts', 'karate'] },
  { emoji: '🥅', name: 'Goal Net', keywords: ['goal', 'sport'] },
  { emoji: '⛳', name: 'Flag in Hole', keywords: ['golf', 'flag'] },
  { emoji: '🏌️', name: 'Golfing', keywords: ['golf', 'sport'] },
  { emoji: '🏇', name: 'Horse Racing', keywords: ['horse', 'racing', 'sport'] },
  { emoji: '🧘', name: 'Person in Lotus Position', keywords: ['yoga', 'meditation'] },
  
  // Work & Office
  { emoji: '💼', name: 'Briefcase', keywords: ['briefcase', 'work', 'business', 'office', 'career'] },
  { emoji: '💼', name: 'Briefcase', keywords: ['suitcase', 'work'] },
  { emoji: '📂', name: 'Open File Folder', keywords: ['folder', 'open', 'files'] },
  { emoji: '📁', name: 'File Folder', keywords: ['folder', 'closed', 'files'] },
  { emoji: '📋', name: 'Clipboard', keywords: ['clipboard', 'list', 'checklist', 'tasks'] },
  { emoji: '📊', name: 'Bar Chart', keywords: ['chart', 'graph', 'data', 'analytics', 'stats'] },
  { emoji: '📈', name: 'Chart Increasing', keywords: ['chart', 'growth', 'up', 'trend'] },
  { emoji: '📉', name: 'Chart Decreasing', keywords: ['chart', 'down', 'trend', 'decrease'] },
  { emoji: '📌', name: 'Pushpin', keywords: ['pin', 'location', 'mark'] },
  { emoji: '📍', name: 'Round Pushpin', keywords: ['pin', 'location', 'map'] },
  { emoji: '📎', name: 'Paperclip', keywords: ['paperclip', 'attachment', 'file'] },
  { emoji: '🖇️', name: 'Linked Paperclips', keywords: ['paperclips', 'linked'] },
  { emoji: '📏', name: 'Straight Ruler', keywords: ['ruler', 'measure', 'straight'] },
  { emoji: '📐', name: 'Triangular Ruler', keywords: ['ruler', 'triangle', 'measure'] },
  { emoji: '✂️', name: 'Scissors', keywords: ['scissors', 'cut'] },
  { emoji: '🗂️', name: 'Card Index Dividers', keywords: ['dividers', 'organize', 'files'] },
  { emoji: '🗄️', name: 'File Cabinet', keywords: ['cabinet', 'files', 'storage'] },
  { emoji: '🗃️', name: 'Card File Box', keywords: ['card', 'box', 'files'] },
  { emoji: '🗑️', name: 'Wastebasket', keywords: ['trash', 'delete', 'waste'] },
  { emoji: '🔒', name: 'Locked', keywords: ['lock', 'secure', 'private'] },
  { emoji: '🔓', name: 'Unlocked', keywords: ['unlock', 'open', 'access'] },
  { emoji: '🔐', name: 'Locked with Key', keywords: ['lock', 'key', 'secure'] },
  { emoji: '🔑', name: 'Key', keywords: ['key', 'unlock', 'access'] },
  { emoji: '🗝️', name: 'Old Key', keywords: ['key', 'old', 'antique'] },
  { emoji: '🔨', name: 'Hammer', keywords: ['hammer', 'tool', 'fix'] },
  { emoji: '🪓', name: 'Axe', keywords: ['axe', 'tool'] },
  { emoji: '⛏️', name: 'Pick', keywords: ['pick', 'tool', 'mining'] },
  { emoji: '🔧', name: 'Wrench', keywords: ['wrench', 'tool', 'fix'] },
  { emoji: '🪛', name: 'Screwdriver', keywords: ['screwdriver', 'tool'] },
  { emoji: '🔩', name: 'Nut and Bolt', keywords: ['nut', 'bolt', 'screw'] },
  { emoji: '⚙️', name: 'Gear', keywords: ['gear', 'settings', 'mechanical'] },
  { emoji: '🗜️', name: 'Clamp', keywords: ['clamp', 'tool'] },
  { emoji: '⚖️', name: 'Balance Scale', keywords: ['scale', 'balance', 'justice'] },
  { emoji: '🦯', name: 'White Cane', keywords: ['cane', 'accessibility'] },
  { emoji: '🔗', name: 'Link', keywords: ['link', 'chain', 'connect'] },
  { emoji: '⛓️', name: 'Chains', keywords: ['chains', 'link'] },
  { emoji: '🧰', name: 'Toolbox', keywords: ['toolbox', 'tools'] },
  { emoji: '🧲', name: 'Magnet', keywords: ['magnet', 'attraction'] },
  { emoji: '🪜', name: 'Ladder', keywords: ['ladder', 'climb'] },
  
  // Science & Technology
  { emoji: '🔬', name: 'Microscope', keywords: ['microscope', 'science', 'lab'] },
  { emoji: '🔭', name: 'Telescope', keywords: ['telescope', 'science', 'space'] },
  { emoji: '📡', name: 'Satellite Antenna', keywords: ['satellite', 'antenna', 'signal'] },
  { emoji: '💉', name: 'Syringe', keywords: ['syringe', 'medical', 'vaccine'] },
  { emoji: '🩸', name: 'Drop of Blood', keywords: ['blood', 'medical'] },
  { emoji: '💊', name: 'Pill', keywords: ['pill', 'medicine', 'drug'] },
  { emoji: '🩹', name: 'Adhesive Bandage', keywords: ['bandage', 'bandaid', 'medical'] },
  { emoji: '🩺', name: 'Stethoscope', keywords: ['stethoscope', 'medical', 'doctor'] },
  { emoji: '🧬', name: 'DNA', keywords: ['dna', 'science', 'biology'] },
  { emoji: '🧪', name: 'Test Tube', keywords: ['test', 'tube', 'science', 'lab'] },
  { emoji: '🧫', name: 'Petri Dish', keywords: ['petri', 'dish', 'science', 'lab'] },
  { emoji: '🌡️', name: 'Thermometer', keywords: ['thermometer', 'temperature', 'weather'] },
  { emoji: '🏷️', name: 'Label', keywords: ['label', 'tag', 'price'] },
  { emoji: '🔖', name: 'Bookmark', keywords: ['bookmark', 'save', 'mark'] },
  
  // Extras for variety
  { emoji: '🎵', name: 'Musical Note', keywords: ['music', 'note', 'song'] },
  { emoji: '🎶', name: 'Musical Notes', keywords: ['music', 'notes', 'songs'] },
  { emoji: '🎤', name: 'Microphone', keywords: ['microphone', 'mic', 'sing'] },
  { emoji: '🎧', name: 'Headphone', keywords: ['headphone', 'music', 'listen'] },
  { emoji: '🎸', name: 'Guitar', keywords: ['guitar', 'music', 'instrument'] },
  { emoji: '🎹', name: 'Musical Keyboard', keywords: ['piano', 'keyboard', 'music'] },
  { emoji: '🥁', name: 'Drum', keywords: ['drum', 'music', 'beat'] },
  { emoji: '🎺', name: 'Trumpet', keywords: ['trumpet', 'music', 'horn'] },
  { emoji: '🎻', name: 'Violin', keywords: ['violin', 'music', 'instrument'] },
  { emoji: '🪗', name: 'Accordion', keywords: ['accordion', 'music'] },
  { emoji: '🎷', name: 'Saxophone', keywords: ['saxophone', 'music', 'sax'] },
  { emoji: '🪕', name: 'Banjo', keywords: ['banjo', 'music'] },
  { emoji: '🎯', name: 'Direct Hit', keywords: ['target', 'dart', 'aim', 'goal', 'bullseye'] },
  
  // More symbols and misc
  { emoji: '💫', name: 'Dizzy', keywords: ['dizzy', 'star', 'sparkle'] },
  { emoji: '⚡', name: 'High Voltage', keywords: ['lightning', 'bolt', 'electric', 'power', 'fast'] },
  { emoji: '💥', name: 'Collision', keywords: ['collision', 'explosion', 'bang'] },
  { emoji: '💢', name: 'Anger Symbol', keywords: ['anger', 'angry', 'mad'] },
  { emoji: '💤', name: 'Zzz', keywords: ['sleep', 'zzz', 'tired'] },
  { emoji: '💨', name: 'Dashing Away', keywords: ['wind', 'fast', 'speed'] },
  { emoji: '🌊', name: 'Water Wave', keywords: ['wave', 'water', 'ocean'] },
  { emoji: '🌋', name: 'Volcano', keywords: ['volcano', 'eruption'] },
  { emoji: '🗻', name: 'Mount Fuji', keywords: ['mountain', 'fuji', 'japan'] },
  { emoji: '🗾', name: 'Map of Japan', keywords: ['map', 'japan'] },
  { emoji: '🗺️', name: 'World Map', keywords: ['map', 'world', 'globe'] },
  { emoji: '🧭', name: 'Compass', keywords: ['compass', 'navigation', 'direction'] },
  { emoji: '🏔️', name: 'Snow-Capped Mountain', keywords: ['mountain', 'snow', 'peak'] },
  { emoji: '⛰️', name: 'Mountain', keywords: ['mountain', 'peak'] },
  { emoji: '🏕️', name: 'Camping', keywords: ['camping', 'tent', 'outdoors'] },
  { emoji: '🏖️', name: 'Beach with Umbrella', keywords: ['beach', 'umbrella', 'vacation'] },
  { emoji: '🏜️', name: 'Desert', keywords: ['desert', 'sand'] },
  { emoji: '🏝️', name: 'Desert Island', keywords: ['island', 'desert', 'tropical'] },
  { emoji: '🏞️', name: 'National Park', keywords: ['park', 'nature', 'outdoors'] },
  { emoji: '🏟️', name: 'Stadium', keywords: ['stadium', 'sports', 'arena'] },
  { emoji: '🏛️', name: 'Classical Building', keywords: ['building', 'classical', 'architecture'] },
  { emoji: '🏗️', name: 'Construction', keywords: ['construction', 'building', 'work'] },
  { emoji: '🧱', name: 'Brick', keywords: ['brick', 'building', 'construction'] },
  { emoji: '🏘️', name: 'Houses', keywords: ['houses', 'village', 'residential'] },
  { emoji: '🏚️', name: 'Derelict House', keywords: ['house', 'derelict', 'abandoned'] },
  { emoji: '🏠', name: 'House', keywords: ['house', 'home', 'residence'] },
  { emoji: '🏡', name: 'House with Garden', keywords: ['house', 'garden', 'home'] },
  { emoji: '🏢', name: 'Office Building', keywords: ['office', 'building', 'work'] },
  { emoji: '🏣', name: 'Japanese Post Office', keywords: ['post', 'office', 'japan'] },
  { emoji: '🏤', name: 'Post Office', keywords: ['post', 'office'] },
  { emoji: '🏥', name: 'Hospital', keywords: ['hospital', 'medical', 'health'] },
  { emoji: '🏦', name: 'Bank', keywords: ['bank', 'money', 'finance'] },
  { emoji: '🏨', name: 'Hotel', keywords: ['hotel', 'accommodation', 'travel'] },
  { emoji: '🏩', name: 'Love Hotel', keywords: ['hotel', 'love'] },
  { emoji: '🏪', name: 'Convenience Store', keywords: ['store', 'convenience', 'shop'] },
  { emoji: '🏫', name: 'School', keywords: ['school', 'education', 'learning'] },
  { emoji: '🏬', name: 'Department Store', keywords: ['store', 'department', 'shop'] },
  { emoji: '🏭', name: 'Factory', keywords: ['factory', 'industry', 'manufacturing'] },
  { emoji: '🏯', name: 'Japanese Castle', keywords: ['castle', 'japan', 'fortress'] },
  { emoji: '🏰', name: 'Castle', keywords: ['castle', 'fortress', 'medieval'] },
  { emoji: '💒', name: 'Wedding', keywords: ['wedding', 'chapel', 'marriage'] },
  { emoji: '🗼', name: 'Tokyo Tower', keywords: ['tower', 'tokyo', 'japan'] },
  { emoji: '🗽', name: 'Statue of Liberty', keywords: ['statue', 'liberty', 'new', 'york'] },
  { emoji: '⛪', name: 'Church', keywords: ['church', 'religion', 'christian'] },
  { emoji: '🕌', name: 'Mosque', keywords: ['mosque', 'islam', 'religion'] },
  { emoji: '🛕', name: 'Hindu Temple', keywords: ['temple', 'hindu', 'religion'] },
  { emoji: '🕍', name: 'Synagogue', keywords: ['synagogue', 'jewish', 'religion'] },
  { emoji: '⛩️', name: 'Shinto Shrine', keywords: ['shrine', 'shinto', 'japan'] },
  { emoji: '🕋', name: 'Kaaba', keywords: ['kaaba', 'islam', 'mecca'] },
  { emoji: '⛲', name: 'Fountain', keywords: ['fountain', 'water', 'decoration'] },
  { emoji: '⛺', name: 'Tent', keywords: ['tent', 'camping', 'outdoors'] },
  { emoji: '🌁', name: 'Foggy', keywords: ['foggy', 'weather', 'cloudy'] },
  { emoji: '🌃', name: 'Night with Stars', keywords: ['night', 'stars', 'city'] },
  { emoji: '🏙️', name: 'Cityscape', keywords: ['city', 'urban', 'skyline'] },
  { emoji: '🌄', name: 'Sunrise Over Mountains', keywords: ['sunrise', 'mountains', 'morning'] },
  { emoji: '🌅', name: 'Sunrise', keywords: ['sunrise', 'morning', 'dawn'] },
  { emoji: '🌆', name: 'Cityscape at Dusk', keywords: ['city', 'dusk', 'evening'] },
  { emoji: '🌇', name: 'Sunset', keywords: ['sunset', 'evening', 'dusk'] },
  { emoji: '🌉', name: 'Bridge at Night', keywords: ['bridge', 'night', 'city'] },
  { emoji: '♨️', name: 'Hot Springs', keywords: ['hot', 'springs', 'onsen'] },
  { emoji: '🎠', name: 'Carousel Horse', keywords: ['carousel', 'horse', 'amusement'] },
  { emoji: '🎡', name: 'Ferris Wheel', keywords: ['ferris', 'wheel', 'amusement'] },
  { emoji: '🎢', name: 'Roller Coaster', keywords: ['roller', 'coaster', 'amusement'] },
  { emoji: '💈', name: 'Barber Pole', keywords: ['barber', 'pole', 'haircut'] },
  { emoji: '🎪', name: 'Circus Tent', keywords: ['circus', 'tent', 'entertainment'] },
  { emoji: '🚂', name: 'Locomotive', keywords: ['train', 'locomotive', 'steam'] },
  { emoji: '🚃', name: 'Railway Car', keywords: ['train', 'car', 'railway'] },
  { emoji: '🚄', name: 'High-Speed Train', keywords: ['train', 'high', 'speed', 'bullet'] },
  { emoji: '🚅', name: 'Bullet Train', keywords: ['train', 'bullet', 'fast'] },
  { emoji: '🚆', name: 'Train', keywords: ['train', 'railway'] },
  { emoji: '🚇', name: 'Metro', keywords: ['metro', 'subway', 'underground'] },
  { emoji: '🚈', name: 'Light Rail', keywords: ['light', 'rail', 'tram'] },
  { emoji: '🚉', name: 'Station', keywords: ['station', 'train', 'railway'] },
  { emoji: '🚊', name: 'Tram', keywords: ['tram', 'streetcar'] },
  { emoji: '🚝', name: 'Monorail', keywords: ['monorail', 'train'] },
  { emoji: '🚞', name: 'Mountain Railway', keywords: ['mountain', 'railway', 'train'] },
  { emoji: '🚋', name: 'Tram Car', keywords: ['tram', 'car'] },
  { emoji: '🚌', name: 'Bus', keywords: ['bus', 'public', 'transport'] },
  { emoji: '🚍', name: 'Oncoming Bus', keywords: ['bus', 'oncoming'] },
  { emoji: '🚎', name: 'Trolleybus', keywords: ['trolleybus', 'electric', 'bus'] },
  { emoji: '🚐', name: 'Minibus', keywords: ['minibus', 'van'] },
  { emoji: '🚑', name: 'Ambulance', keywords: ['ambulance', 'emergency', 'medical'] },
  { emoji: '🚒', name: 'Fire Engine', keywords: ['fire', 'engine', 'truck', 'emergency'] },
  { emoji: '🚓', name: 'Police Car', keywords: ['police', 'car', 'cop'] },
  { emoji: '🚔', name: 'Oncoming Police Car', keywords: ['police', 'car', 'oncoming'] },
  { emoji: '🚕', name: 'Taxi', keywords: ['taxi', 'cab', 'yellow'] },
  { emoji: '🚖', name: 'Oncoming Taxi', keywords: ['taxi', 'oncoming'] },
  { emoji: '🚗', name: 'Automobile', keywords: ['car', 'automobile', 'vehicle'] },
  { emoji: '🚘', name: 'Oncoming Automobile', keywords: ['car', 'oncoming'] },
  { emoji: '🚙', name: 'Sport Utility Vehicle', keywords: ['suv', 'car', 'vehicle'] },
  { emoji: '🚚', name: 'Delivery Truck', keywords: ['truck', 'delivery', 'package'] },
  { emoji: '🚛', name: 'Articulated Lorry', keywords: ['truck', 'lorry', 'big'] },
  { emoji: '🚜', name: 'Tractor', keywords: ['tractor', 'farm', 'agriculture'] },
  { emoji: '🏎️', name: 'Racing Car', keywords: ['racing', 'car', 'speed'] },
  { emoji: '🏍️', name: 'Motorcycle', keywords: ['motorcycle', 'bike', 'vehicle'] },
  { emoji: '🛵', name: 'Motor Scooter', keywords: ['scooter', 'motor', 'vehicle'] },
  { emoji: '🦽', name: 'Manual Wheelchair', keywords: ['wheelchair', 'manual', 'accessibility'] },
  { emoji: '🦼', name: 'Motorized Wheelchair', keywords: ['wheelchair', 'motorized', 'accessibility'] },
  { emoji: '🛴', name: 'Kick Scooter', keywords: ['scooter', 'kick', 'vehicle'] },
  { emoji: '🚲', name: 'Bicycle', keywords: ['bicycle', 'bike', 'cycling'] },
  { emoji: '🛴', name: 'Kick Scooter', keywords: ['scooter', 'manual'] },
  { emoji: '🛹', name: 'Skateboard', keywords: ['skateboard', 'sport', 'skate'] },
  { emoji: '🛼', name: 'Roller Skate', keywords: ['roller', 'skate', 'skating'] },
  { emoji: '🚁', name: 'Helicopter', keywords: ['helicopter', 'chopper', 'air'] },
  { emoji: '🛸', name: 'Flying Saucer', keywords: ['ufo', 'alien', 'spaceship'] },
  { emoji: '🚀', name: 'Rocket', keywords: ['rocket', 'space', 'launch', 'fast'] },
  { emoji: '🛩️', name: 'Small Airplane', keywords: ['airplane', 'small', 'private'] },
  { emoji: '✈️', name: 'Airplane', keywords: ['airplane', 'plane', 'flight'] },
  { emoji: '🛫', name: 'Airplane Departure', keywords: ['airplane', 'departure', 'takeoff'] },
  { emoji: '🛬', name: 'Airplane Arrival', keywords: ['airplane', 'arrival', 'landing'] },
  { emoji: '🪂', name: 'Parachute', keywords: ['parachute', 'skydiving', 'air'] },
  { emoji: '💺', name: 'Seat', keywords: ['seat', 'chair', 'sit'] },
  { emoji: '🚢', name: 'Ship', keywords: ['ship', 'boat', 'cruise'] },
  { emoji: '🚤', name: 'Speedboat', keywords: ['speedboat', 'fast', 'boat'] },
  { emoji: '🛥️', name: 'Motor Boat', keywords: ['motor', 'boat'] },
  { emoji: '🛳️', name: 'Passenger Ship', keywords: ['ship', 'passenger', 'cruise'] },
  { emoji: '⛴️', name: 'Ferry', keywords: ['ferry', 'boat', 'transport'] },
  { emoji: '🛶', name: 'Canoe', keywords: ['canoe', 'boat', 'paddle'] },
  { emoji: '🚁', name: 'Helicopter', keywords: ['helicopter', 'chopper'] },
  { emoji: '⛽', name: 'Fuel Pump', keywords: ['fuel', 'pump', 'gas', 'station'] },
  { emoji: '🚧', name: 'Construction', keywords: ['construction', 'warning', 'roadwork'] },
  { emoji: '🚦', name: 'Vertical Traffic Light', keywords: ['traffic', 'light', 'signal'] },
  { emoji: '🚥', name: 'Horizontal Traffic Light', keywords: ['traffic', 'light', 'horizontal'] },
  { emoji: '🗺️', name: 'World Map', keywords: ['map', 'world', 'globe'] },
  { emoji: '🗿', name: 'Moai', keywords: ['moai', 'statue', 'easter', 'island'] },
  { emoji: '🗽', name: 'Statue of Liberty', keywords: ['statue', 'liberty', 'usa'] },
  { emoji: '🗼', name: 'Tokyo Tower', keywords: ['tower', 'tokyo', 'japan'] },
  { emoji: '🏰', name: 'Castle', keywords: ['castle', 'fortress'] },
  { emoji: '🏯', name: 'Japanese Castle', keywords: ['castle', 'japanese'] },
  { emoji: '🏟️', name: 'Stadium', keywords: ['stadium', 'sports'] },
  { emoji: '🏛️', name: 'Classical Building', keywords: ['building', 'classical'] },
  { emoji: '⛲', name: 'Fountain', keywords: ['fountain', 'water'] },
  { emoji: '⛺', name: 'Tent', keywords: ['tent', 'camping'] },
  { emoji: '🌁', name: 'Foggy', keywords: ['foggy', 'cloudy'] },
  { emoji: '🌃', name: 'Night with Stars', keywords: ['night', 'stars', 'city'] },
  { emoji: '🏙️', name: 'Cityscape', keywords: ['city', 'urban'] },
  { emoji: '🌄', name: 'Sunrise Over Mountains', keywords: ['sunrise', 'mountains'] },
  { emoji: '🌅', name: 'Sunrise', keywords: ['sunrise', 'morning'] },
  { emoji: '🌆', name: 'Cityscape at Dusk', keywords: ['city', 'dusk'] },
  { emoji: '🌇', name: 'Sunset', keywords: ['sunset', 'evening'] },
  { emoji: '🌉', name: 'Bridge at Night', keywords: ['bridge', 'night'] },
  { emoji: '♨️', name: 'Hot Springs', keywords: ['hot', 'springs', 'onsen'] },
];

// Filter out duplicates - keep only the first occurrence of each emoji
const emojiSet = new Set<string>();
export const EMOJI_DATA: EmojiData[] = EMOJI_DATA_RAW.filter((item) => {
  if (emojiSet.has(item.emoji)) {
    return false;
  }
  emojiSet.add(item.emoji);
  return true;
});

// For backward compatibility, export the original EMOJI_OPTIONS array
export const EMOJI_OPTIONS = EMOJI_DATA.map(item => item.emoji);
